name: Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
    
      - name: Configurar ambiente Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Instalar dependências
        run: go mod download

      - name: Executar testes
        run: go test ./...
        continue-on-error: false

      - name: Checkout tests
        run: |
          if [ $? -eq 0 ]; then
            echo "Tests ok. Build and push docker image."
          else
            echo "Tests Fail. Cancel build and push docker image."
            exit 1
          fi

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build e Push da Imagem Docker
        run: |
          docker build -t rmottanet/coinsnark:go-latest .
          docker push rmottanet/coinsnark:go-latest
