name: Tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Executar Testes
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar ambiente Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'

    - name: Instalar dependências
      run: go mod download

    - name: Executar testes
      run: go test ./...
