name: Tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Executar Testes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: 1.20
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar ambiente Go
      uses: actions/setup-go@v4
      with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version

    - name: Instalar dependências
      run: go mod tidy

    - name: Executar testes
      run: go test ./...
